Rename mixed-case directories to all lowercase
Resolves issue where mixed-case directories were causing NoClassDefFoundError exceptions in
Jenkins for the classes contained in these directories.